name: Api Gateway CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    uses: bizno-marketplace/.github/.github/workflows/ci-reusable.yml@master
    with:
        run-unit-tests: false
        run-integration-tests: false
        run-bdd-tests: false
        run-coverage: false
        coverage-threshold: 0
